# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.94.3.dev10+g0f4e77b'
__version_tuple__ = version_tuple = (0, 94, 3, 'dev10', 'g0f4e77b')
