name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - python-version: '3.10'
        - python-version: '3.11'
        - python-version: '3.12'
        - python-version: '3.13'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Python 
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          pip install -e .[test,docs]
      - name: Test
        run: pytest --remote-data=any
      - name: Build docs
        run: |
          cd docs
          make html
        